### ISSUE TITLE
Лупюющиеся насмешки

### ISSUE THREAD

**Issue by medadon41** [MoonlyDays/Battle-Tank-Fortress#5]
![20181028210819_1](https://user-images.githubusercontent.com/44553922/47620606-ff060b00-dafc-11e8-866c-84ec368537dd.jpg)
Если на спавне активировать Victory Lap или другую лупюющаяся насмешку, то насмешка с танком не будет активироваться, пока лупюющаяся насмешка не прекратится.

**Comment by MoonlyDays** [comment]
Исправлено блокировкой иных насмешек.
