### ISSUE TITLE
Косметики и оружия с других классов

### ISSUE THREAD

**Issue by TranslitZeBest** [MoonlyDays/Battle-Tank-Fortress#6]
Если выбрать другой класс 2 раза, то заспавнишься за солда с другими шапками и оружием ![image](https://user-images.githubusercontent.com/44553608/47650159-06bec180-db88-11e8-8457-2dc539779ba9.png) 
![image](https://user-images.githubusercontent.com/44553608/47650293-8482cd00-db88-11e8-9991-5b598b694a3e.png) 
![image](https://user-images.githubusercontent.com/44553608/47650307-8cdb0800-db88-11e8-9e83-250be44233c2.png)
![image](https://user-images.githubusercontent.com/44553608/47650312-906e8f00-db88-11e8-9f30-c7bd81a2b619.png)
![image](https://user-images.githubusercontent.com/44553608/47650325-95cbd980-db88-11e8-97d5-446a0dfaa356.png)
![image](https://user-images.githubusercontent.com/44553608/47650369-b5630200-db88-11e8-8ddc-3af82d3e6ca8.png)

**Comment by MoonlyDays** [comment]
Проблема клиента.
